### ISSUE TITLE
Regex on line 94 of normalizer.rb seems to fire incorrectly

### ISSUE THREAD

**Issue by philgooch** [inukshuk/anystyle-parser#28]
I have created a model from journal articles without titles and this is working well. However, I noticed that author labels are getting switched for editor labels in certain circumstances, and I think this regex may be the cause

if authors =~ /[^[:alnum:]]*[Ee]d(s|itors)?[^[:alnum:]]*$/ && !hash.has_key?(:editor)

If I parse the following line

P. Eisenberger and W. A. Reed, Phys. Rev. A 5, 2085 (1972)

I get

[{:journal=>"Phys. Rev. A", :volume=>5, :pages=>"2085", :date=>"1972", :editor=>"Eisenberger, P. and Reed, W.A.", :type=>:article}]

If I change 'Reed' to 'Read' then I get the expected

[{:author=>"Eisenberger, P. and Read, W.A.", :journal=>"Phys. Rev. A", :volume=>5, :pages=>"2085", :date=>"1972", :type=>:article}]

suggesting that the token ending with 'ed,' is causing the regex on line 94 of normalizer.rb to fire

I think it would be better to include a word boundary before '[Ee]d' to ensure that only words starting and ending with this expression are matched. E.g.

if authors =~ /[^[:alnum:]]*\b[Ee]d(s|itors)?\b[^[:alnum:]]*$/ && !hash.has_key?(:editor)

**Comment by inukshuk** [comment]
You're absolutely right — word boundaries were probably the intention behind the `[^[:alnum:]]` there but the star rendered that approach pretty much useless. I fixed this and will push to Rubygems right away.

**Comment by philgooch** [comment]
Thanks, got the latest version. But I wonder if for 'Ed' on its own the full point needs to be enforced.

Consider parsing

K. S. Sohn, D. G. Dempsey, L. Kleinman and Ed Caruthers, Phys. Rev. B 13, 1515 (1976).

Poor old Ed gets eaten and we get

[{:journal=>"Phys. Rev. B", :volume=>13, :pages=>"1515", :date=>"1976", :editor=>"Sohn, K.S. and Dempsey, D.G. and andCaruthers, L.Kleinman", :type=>:article}]

**Comment by inukshuk** [comment]
OK, next attempt. Hope it works now (I added poor old Ed to the test cases to make sure he's fine!)

Thanks again!
