### ISSUE TITLE
usage is not working and 

### ISSUE THREAD

**Issue by bhargavd6** [inukshuk/anystyle-parser#30]
>> require 'anystyle/parser'

>> Anystyle.parse """
    Turing, Alan, Computing Machinery and Intelligence, Mind 59, pp 433-460 (1950)
   """
=> [{
     :type => :article
     :author => "Turing, Alan",
     :title => "Computing Machinery and Intelligence",
     :journal => "Mind",
     :volume => 59,
     :pages => "433–460",
     :year => 1950
   }]

We triend these but not running throwing many errors

**Comment by bhargavd6** [comment]
Please provide how to run after installation with detailed steps

**Comment by inukshuk** [comment]
Please follow the detailed steps provided by the Readme. You will need a good knowledge of Ruby to use the parser properly. If you report errors here, you need to provide more details (saying something 'throws many errors' is not helpful at all).

Having said that, put this in your Gemfile:

    source 'https://rubygems.org'
    gem 'anystyle-parser'

Put this in a file `parse.rb`:

    require 'bundler/setup'
    require 'anystyle/parser'

    puts Anystyle.parse """
      Turing, Alan, Computing Machinery and Intelligence, Mind 59, pp 433-460 (1950)
    """

And run `ruby parse.rb` -- this should get you started.
