### ISSUE TITLE
Bibetex Error when running program

### ISSUE THREAD

**Issue by bhargavd6** [inukshuk/anystyle-parser#31]
[root@localhost anystyle]# ruby parser.rb 
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bibtex (LoadError)
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from parser.rb:4:in `<main>'
[root@localhost anystyle]#

**Comment by bhargavd6** [comment]
Runing with changes suggested in previous suggestion but still getting below issues

again:

/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- wapiti (LoadError)
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'

**Comment by bhargavd6** [comment]
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- wapiti (LoadError)
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'


Please help and provide details steps to run the script and exact locations using Linux/Unix command line program..

Please provide sample program if possible to invoke the parser

**Comment by inukshuk** [comment]
I am sorry, but I cannot do your work for you. The example I posted in the other thread is a 'full sample program' that works out of the box if you have a properly configured Ruby environment with RubyGems and Bundler. The errors you posted above indicate that your environment is probably not set up correctly or that you installed the parser without its dependencies -- I'd recommend setting up your environment with a tool like chruby, rbenv, or rvm.

**Comment by bhargavd6** [comment]
Thank you for reply ... thosee errors disappeared... understand that these errors are due to dependency package recenyl tehre is an error related to version number for our anystyle parser

please help how and where we need to update or change version number :+1: 

present error is below:

[root@localhost lib]# ruby sample.rb 
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- anystyle/parser/version (LoadError)
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /root/workspace/anystyle-parser/lib/anystyle/parser.rb:9:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from sample.rb:2:in `<main>'
[root@localhost lib]# pwd
/root/workspace/anystyle-parser/lib
[root@localhost lib]# 

and my sample program to invoke parser is as below: please help how it can be called:

/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- anystyle/parser/version (LoadError)
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /root/workspace/anystyle-parser/lib/anystyle/parser.rb:9:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from sample.rb:2:in `<main>'
[root@localhost lib]# pwd
/root/workspace/anystyle-parser/lib
Should i run the program from main directory or from /lib/* location, please help

**Comment by bhargavd6** [comment]
[root@localhost lib]# ls
anystyle  sample.rb
[root@localhost lib]# ruby sample.rb 
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- anystyle/parser/version (LoadError)
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /root/workspace/anystyle-parser/lib/anystyle/parser.rb:9:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from sample.rb:2:in `<main>'
[root@localhost lib]# pwd
/root/workspace/anystyle-parser/lib
[root@localhost lib]#
