### ISSUE TITLE
Errors related to missing library

### ISSUE THREAD

**Issue by sajinh** [inukshuk/anystyle-parser#33]
After installing anystyle-parser, and loading it in an irb session as follows gives

<pre>
irb(main):002:0> require 'anystyle/parser'
LoadError: cannot load such file -- language_detector
	from /usr/local/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/local/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/local/lib/ruby/gems/1.9.1/gems/anystyle-parser-0.7.1/lib/anystyle/parser/parser.rb:27:in `<class:Parser>'
	from /usr/local/lib/ruby/gems/1.9.1/gems/anystyle-parser-0.7.1/lib/anystyle/parser/parser.rb:4:in `<module:Parser>'
	from /usr/local/lib/ruby/gems/1.9.1/gems/anystyle-parser-0.7.1/lib/anystyle/parser/parser.rb:2:in `<module:Anystyle>'
	from /usr/local/lib/ruby/gems/1.9.1/gems/anystyle-parser-0.7.1/lib/anystyle/parser/parser.rb:1:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/local/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/local/lib/ruby/gems/1.9.1/gems/anystyle-parser-0.7.1/lib/anystyle/parser.rb:14:in `<top (required)>'
</pre>

Although the library is loaded all right, the parse method cannot be found

<pre>
irb(main):007:0> Anystyle.parse 
NoMethodError: undefined method `parse' for Anystyle:Module

</pre>

saji

**Comment by philgooch** [comment]
I got this error when I installed Anystyle on an instance yesterday. This can be resolved by doing

gem install language_detector

**Comment by inukshuk** [comment]
Ah, yes, I added language detection recently, but it's supposed to be an optional feature. I'll make it so that you don't need to install the gem if you don't want to. If you do want to have language detection, you need to install the gem from GitHub not RubyGems for later versions of Ruby!

**Comment by inukshuk** [comment]
Version 0.7.2 should not fail anymore if language_detector is not installed.
