### ISSUE TITLE
Citation number is truncated in BibTeX and in CiteProc/JSON

### ISSUE THREAD

**Issue by AmirSimantov** [inukshuk/anystyle-parser#35]
If the citation number includes a punctuation mark, the value that is exported is truncated to an integer leaving any other characters behind. 

All the following input citation number will result with citation_number = 1
1.1.4.1
1,123
1b

Note that parsing itself goes well. This happens both in BibTeX and in CiteProc/JSON (but not in XML).

I was using the anystyle.io web interface.

Thanks!

**Comment by inukshuk** [comment]
Thanks for reporting!

This should be fixed in 0.7.3, up on anystyle.io shortly.

**Comment by AmirSimantov** [comment]
That was quick!
