### ISSUE TITLE
Parsing from .txt groups things together that don't belong (e.g. "Music 42")

### ISSUE THREAD

**Issue by emilyhopkins** [inukshuk/anystyle-parser#36]
Thanks for the awesome parser! It's largely been working very well for me; it's a very friendly interface.

When parsing from a plain text file that I copy-pasted into the parser, a few times it has grouped words and numbers together that don't belong.

For example, "Music 42" (journal title and volume number) or "Portugal: 2012" (location and publication date). 

It's not consistent enough to be obvious why it's doing it on these cases. It needs to err on the side of separating things more, not less, so that corrections can be made and I can use those corrections to teach the parser :)

**Comment by inukshuk** [comment]
Can you confirm that there are indeed spaces between the tokens in question in the pasted text? Also, if you provide the full reference that's causing the issue it would be much easier to debug. Thanks!

**Comment by emilyhopkins** [comment]
At work I was pasting from TextEdit. I've tried to replicate the problem at home, pasting from Mousepad, but it parses fine. It seems like TextEdit is introducing the problem: unicode spaces that Anystyle isn't recognizing. For example, "foo bar" (as entered here) parses as one block on AnyStyle (using a unicode en-space, U+2002)

Maybe this is more of a feature request than a bug report, since I don't know what your unicode support is like right now, but it seems like it would be useful for the parser.

**Comment by inukshuk** [comment]
Ah, thanks for looking into this!

This should be fixed in the next release.

**Comment by emilyhopkins** [comment]
Cool, thanks!
