### ISSUE TITLE
Differences in output from different instances of anystyle

### ISSUE THREAD

**Issue by jocelynpender** [inukshuk/anystyle-parser#39]
I was working through the irb session illustration from the readme after installing anystyle. I copied and pasted the commands with example references, but received different parsing results than the illustration. For example, 

puts Anystyle.parse('Auster, Paul. The Art of Hunger. Expanded. New York: Penguin, 1997.', :bibtex).to_s

@book{auster1997a,
  author = {Auster, Paul},
  title = {The Art of Hunger},
  publisher = {Penguin},
  date = {1997},
  edition = {Expanded},
  language = {},
  address = {New York}
}
 => nil

This result is different from the result in the irb session in the readme (address vs. location, date vs. year). In addition, I ran this same code twice. The above result is after reinstalling the gem (there were encoding issues, and I was trying to resolve them), and the first result was even worse. The parser was unable to recognize New York as a location or address. (I'm working on ruby 1.9.3 through ssh to a dreamhost account).

Are there reasons why anystyle would give different results between sessions? I assume the training data that comes with it is the same each time I install. Any comment on this subject would be appreciated.

Thanks,
Jocelyn

**Comment by inukshuk** [comment]
The model's labels have been renamed so the output in the Readme may not be up to date. Also, in the example the result is converted to bibtex which may not be the best format for further processing (also try the default format by skipping the second parameter or `:citeproc`).

In any case, using the same model and the same input the result should be identical. If you had encoding issues that might have thrown the parser off.

If you're wondering about the language field, for the language parsing to work you need to install an additional Gem

**Comment by inukshuk** [comment]
You can run `Anystyle.parser.model.labels` to see the labels used by the current model.

**Comment by jocelynpender** [comment]
Thank you for the quick response.

A further question for clarification about the model, does the example use
the same training model as the one that's distributed? If not, is the more
recent training model available for download?

Thank you,
Jocelyn

**Comment by inukshuk** [comment]
There is a default model that ships with the Gem. (The training data is in the repository)

Additionally, on anystyle.io we have a model that is in flux because it can be trained publicly. We actually need to reset it from time to time, because the training data is not always good and the model deteriorates.

**Comment by Pryanga** [comment]
Dear Mr. inukshuk, 

I am analyzing Anystyle parser and I would like to know the labels used in the model. 
With `Anystyle.parser.model.labels` the output is:
`["accessed", "author", "authority", "booktitle", "date", "director", "doi", "edition", "editor", "event", "genre", "isbn", "journal", "location", "medium", "note", "pages", "producer", "publisher", "section", "source", "title", "translator", "unknown", "url", "volume"]`

However, when I set the format = :citeproc, there are more labels than the ones specified above.
`irb(main):033:0> Myprs.parse("Lombard, M.-A. 1989. “Tchador à l’école: deux mois d’un débat qui divise la France.” Le Figaro, 27 November, p. 10.", format = :citeproc)
=> [{"author"=>[{"family"=>"Lombard", "given"=>"M.-A."}], "title"=>"Tchador à l’école: deux mois d’un débat qui divise la France.", "container-title"=>"Le Figaro", "volume"=>"27", "page"=>"10", "language"=>"", "id"=>"lombard1989a", "issued"=>{"date-parts"=>[[1989, 11]]}, "type"=>"article-journal"}]
`
Is there a way that I can view/extract all the labels (along with its sub-labels) used in the model?

Your help will aid me in my school project.
