### ISSUE TITLE
Working with php

### ISSUE THREAD

**Issue by Gobisan** [inukshuk/anystyle-parser#42]
Hello sir.The library works extremely well in the terminal, but the problem is that when I try to run the ruby script via php (by using system()), by making the script to parse the given string(through php to ruby) and store it in a file,nothing happens.The data is not getting stored in the file.

PHP code : 
       
<?php
	if (isset($_POST["ref"])) {
	$reference=$_POST["ref"];
	$cmd="ruby t.rb ";
	system($cmd);	
	}
	?>

RUBY CODE :
 
require 'anystyle/parser'
  ref='Poe, Edgar A. Essays and Reviews. New York: Library of America, 1984.'
  s=Anystyle.parse('Auster, Paul. The Art of Hunger. Expanded. New York: Penguin, 1997.',   :bibtex).to_s 
  open('1.txt', 'w') do |f|
  f.puts("\r\n") 
  f.puts s
  end

The ruby code(above) works perfectly in the terminal.But when I try to run it through php , nothing happens.A little help would be appretiated.Thank you.

**Comment by inukshuk** [comment]
I suspect there is an error when you execute the script (what's the return value and status of your system call?); probably because the web server process does not have access to Ruby or to the Gems you installed. (When you run the code on the terminal do you run it as the web server user or a different one?)

**Comment by Gobisan** [comment]
Thank you very much for your reply.

Actually it did not display any output.Only error number 22527 was shown,when i made it to display errors(by using `error_reporting(E_ALL);` in php).

> When the ruby script(alone) is  run (through terminal), it gives no errors.It works perfectly fine.

But, when i call the very same script through php via.a localhost (using apache server),it does not display any output.I have created a UI wherein a submit button is present.When i press that button the ruby script will be called.

The error seems to occur exactly after i use this code
`s=Anystyle.parse 'Auster, Paul. The Art of Hunger. Expanded. New York: Penguin, 1997.'`

I believe that maybe gems are not being accessed by the server,but it was working fine when i used the Json gem(for example) alone .I have attached my files,so that maybe you can check it.

**Comment by inukshuk** [comment]
The PHP `system` command has a return value; you need to use this or an other means to capture `stdout` and `stderr` to see what's going on; alternatively you can add some kind of logging to the Ruby code.

It's likely the case that the gems can't be loaded (json may also be part of the standard library) -- it all depends on how you set up Ruby on the server. Like I said earlier, did you run the code from the Terminal with the same user and environment that owns the web server process? That would be the easiest way to find out whether or not your setup is working.

**Comment by inukshuk** [comment]
Closing this as it's not really related to the parser.
