### ISSUE TITLE
This is rather a question.Not an issue.How do i export the data in ruby hash to citeprocJSON or BIBJSON??

### ISSUE THREAD

**Issue by Gobisan** [inukshuk/anystyle-parser#43]
I am able to render the data in simple JSON format(by using the functio .to_json).However, it does not seem to segregate the names(with initials) separately.Also i happened to read an issue,and you have already mentioned that the data if rendered in citeproc-JSON/BIBJSON formats, will segregate the names separately.How should that be done?Is there any function to render/convert the data in to such formats?Can you provide a sample code?

**Comment by inukshuk** [comment]
Please consult the [README](https://github.com/inukshuk/anystyle-parser#parsing) -- just pass the format (`:citeproc` or `:bibtex`) as the second parameter to the parse method.
