### ISSUE TITLE
Bug in `normalize_names` when author is `Surname, Given Initial`

### ISSUE THREAD

**Issue by philgooch** [inukshuk/anystyle-parser#47]
Unfortunately the `vancouver-name-fix` PR https://github.com/inukshuk/anystyle-parser/pull/44 has introduced a bug where author strings such as

`Kates, Robert W`

and

`Poe, Edgar A`

will now get parsed as

`Kates, Robert and W.`

and

`Poe, Edgar and A.`

This PR should fix this bug: https://github.com/inukshuk/anystyle-parser/pull/46

**Comment by inukshuk** [comment]
Thanks for following up on this. I generally find that tweaking the normalizer in a generic way is extremely difficult (usually easy to fix local issues with a given data set but usually that breaks expectations of other input...)

**Comment by philgooch** [comment]
Perhaps a better idea than retro-fixing any errors introduced by this is to check whether we have something that looks like Vancouver-style names, and only then add the comma, e.g.

```
if names.match(/^(\p{Lu}[^\s,.]+)\s+([\p{Lu}][\p{Lu}\-]{0,3})(,|$)/)
   names.gsub!(...)
end
```

I'll run some tests
