### ISSUE TITLE
Incorrect volume/issue type

### ISSUE THREAD

**Issue by karthikeyansam** [inukshuk/anystyle-parser#52]
Refer the below citation 
Judge, T., Erez, A., & Bono, J. (1998). The power of being positive: The relation between positive self-concept and job performance, Human Performance, 11(2/3), 167–187.

The issue identified as 2 not 2/3 and like wise it handles only when the number is present, other wise it throws exception error on training while trying with text like Suppl.

Is that anything to do with training?

**Comment by inukshuk** [comment]
This has to do with normalizing the volume/issue numbers. Just added support for your case above. Thanks for reporting!

(The change will be available on anystyle.io shortly)
