### ISSUE TITLE
Getting a 54 error with JSON API

### ISSUE THREAD

**Issue by FlavourDaveMasterDDissle-theDtotheissle** [inukshuk/anystyle-parser#56]
Using the JSON api with python results in a 54 error ('Connection aborted.', error(54, 'Connection reset by peer')).

I tried both 'https://anystyle.io/parse/references.json' and 'https://anystyle.io/parse/references' as URL. Both result in the same 54 error.

i.e.: https://gist.github.com/FlavourDaveMasterDDissle-theDtotheissle/8227e30c1a029f62148bf19a8ca98f50

**Comment by inukshuk** [comment]
Is the API you're using compatible with HTTPS?

**Comment by FlavourDaveMasterDDissle-theDtotheissle** [comment]
yes, they outline in their first example ">>> r = requests.get('https://api.github.com/user', auth=('user', 'pass'))" (http://docs.python-requests.org/en/master/)

**Comment by inukshuk** [comment]
I just tried to connect with python requests using your example and it works just fine. Using your example, I was getting a 400 Bad Request responses -- probably because `data` was not converted to JSON automatically? Passing `data` as a string works:

```>>> import requests
>>> data = '{ "access_token": "YOUR API KEY HERE", "references": ["Turing, Alan, Computing Machinery and Intelligence, Mind 59, pp 433-460 (1950)"]}'
>>> url = 'https://anystyle.io/parse/references.json'
>>> headers = {"Content-Type": "application/json; charset=UTF-8"}
>>> res = requests.post(url, data=data, headers=headers)
>>> res.json()
[{'booktitle': 'Computing Machinery and Intelligence, Mind', 'pages': '433–460', 'language': 'en', 'author': 'Turing, Alan', 'volume': 59, 'type': 'incollection', 'date': '1950'}]```

**Comment by FlavourDaveMasterDDissle-theDtotheissle** [comment]
thank you for your reply!
But even with your code I get this 54 error - is there something wrong with my API-Key? Do I have to activate it somehow?

**Comment by inukshuk** [comment]
No this must be a network problem on your end somewhere. Can you make other connections from the machine on which you're running this? Your requests don't show up on the server log, so they never get there (if there is an issue with your API key you should get a 401 response code).

**Comment by FlavourDaveMasterDDissle-theDtotheissle** [comment]
I tried it from two machines in different networks (university and home) with both 54 errors :(

**Comment by FlavourDaveMasterDDissle-theDtotheissle** [comment]
okay, seems to be a OS X security problem - work's like a charm with Windows. Thank you inukshuk!
