### ISSUE TITLE
Book title taken as Book section in Zotero / Bibtex

### ISSUE THREAD

**Issue by silviaegt** [inukshuk/anystyle-parser#57]
Hey Sylvester!
Thank you so much for developing this!!
I was trying to export my bibliography to Zotero and the parser rightly understood the title as a book title 
![imagen](https://cloud.githubusercontent.com/assets/8223258/20723322/ae7853ee-b62f-11e6-8ee5-b04c32c274ee.png)
However when exporting it to Zotero it parsed it as a book section with an empty chapter name:
![imagen](https://cloud.githubusercontent.com/assets/8223258/20729770/120b6e00-b649-11e6-8d82-be5e7028de47.png)
What could have gone wrong?

**Comment by inukshuk** [comment]
Oh, that's a misunderstanding: 'book title' is actually the term the parser uses when it identifies the reference as a chapter (normally a chapter would have both 'title' and 'book title', obviously) -- so in this case the parser is simply wrong: the reference is a book with a title, while the parser detected a chapter with a book title (and no title).

Why was the parser wrong? Book titles often come right after the editors for chapters in most styles and the parser was (initially) trained with mostly APA-like styles where publication date would come between the editors and the title. That is, the sequence of a list of names, the string '(eds.),' and a title is a strong indicator for book chapters.

Not to worry, though, if you have a lot of references like this, try to parse a few of them and change 'book title' to 'title' and train the model. Alternatively, if you just have a handful references like this it's easier to just fix them by hand and you're good to go.
