### ISSUE TITLE
Identified an issue related with the parser or training

### ISSUE THREAD

**Issue by vijaynaidu** [inukshuk/anystyle-parser#61]
I've identified an issue with the parser. Can you tell me how can i work with getting the expected output. As, of now main issue is **Author** should be "**Social Security Administration**" other than "**Administration, Social Security**"

INPUT:

> Social Security Administration. Social Security Programs Throughout the World: Asia and the Pacific, 2008. Vol. 13. No. 11801. Government Printing Office, 2002.

TRAIN DATA:
`<author>Social Security Administration</author><title>Social Security Programs Throughout the World: Asia and the Pacific, 2008. </title><volume>Vol. 13. No. 11801. </volume><publisher>Government Printing Office, </publisher><date>2002.</date>`
```
Anystyle.parser.train '/var/www/volume/temp_dta/train_test.txt', false
Anystyle.parser.model.save
```

Expected Output:

> @book{**social2002social**,
>   **author = {Social Security Administration},**
>   title = {Social Security Programs Throughout the World: Asia and the Pacific, 2008},
>   volume = {13},
>   publisher = {Government Printing Office},
>   date = {2002},
>   number = {11801},
>   language = {}
> }

What i got output other than expected?

> @book{**administration2002a**,
>   **author = {Administration, Social Security},**
>   title = {Social Security Programs Throughout the World: Asia and the Pacific, 2008},
>   volume = {13},
>   publisher = {Government Printing Office},
>   date = {2002},
>   number = {11801},
>   language = {}
> }

**Comment by inukshuk** [comment]
Depending on the selected output format, the parser will attempt to parse names. Using bibtex or citeproc, all names will be parsed using BibTeX's name format rules. The name 'Social Security Adminstration' is parsed into given name 'Social Security' and last name 'Adminstration' and printed in a 'last, first' format.

There are two things you can do about this: you can keep using bibtex format and use the API provided by bibtex-ruby to print names in a different format. Or you can use a different output format, which does not attempt to parse names at all (like the `normalized` or `hash` format).

**Comment by vijaynaidu** [comment]
@inukshuk Thanks.
