### ISSUE TITLE
Ampersand symbol is replaced to & in the output

### ISSUE THREAD

**Issue by ckannaiah** [inukshuk/anystyle-parser#63]
Hi,

When the input has got & symbol the output is being replaced to "and". Is there anyway that this can be stopped.

I am new to this, so I might be asking you some basic questions.

Thanks,
Chandra

**Comment by inukshuk** [comment]
This depends on the output format you're using. If you want to stay close to the original input, use the XML output -- if you use that format your ampersands should remain unchanged.

However, I doubt that this is the best solution for you. CiteProc/JSON returns the names as an array; and BibTeX uses 'and' per default. For both formats there exist ways to further process the names (e.g., CiteProc/JSON can be fed into a CSL processor with whatever style you need, rendering ampersands as mandated by the style etc.).
