### ISSUE TITLE
https error

### ISSUE THREAD

**Issue by Elbar914** [inukshuk/anystyle-parser#67]
Encounter this error when trying to access the site: 

<img width="999" alt="error anystyleio" src="https://user-images.githubusercontent.com/26442944/28585911-e14a32ee-713f-11e7-8f48-81e1944e6287.png">

**Comment by dconner3** [comment]
I am getting this too when I try http://anystyle.io or https://anystyle.io

**Comment by inukshuk** [comment]
Is this still happening for you? I can connect just fine using Firefox or Chromium.

**Comment by Elbar914** [comment]
@inukshuk it's back up! Thanks.

**Comment by dconner3** [comment]
I can now connect in Chrome and Firefox.
