### ISSUE TITLE
Latest Wapiti

### ISSUE THREAD

**Issue by dominic-sps** [inukshuk/anystyle-parser#71]
I noted that AP uses the gem `wapiti (0.1.1)`. This is very old I guess. Is there any plans to upgrade?
Grobid uses Wapiti version 1.5.0. 

Just to check the latest capability of Wapiti, is it possible to run AP outside of gem. 

PS: I am NOT a ruby person :)

**Comment by inukshuk** [comment]
Not to worry, the version of the `wapiti` Gem is does not reflect the Wapiti version. We [upgraded](https://github.com/inukshuk/wapiti-ruby/blob/master/HISTORY.md#010--2014-02-25) to Wapiti 1.5.0 in version `0.1.0`.
