### ISSUE TITLE
Comments and multiple models

### ISSUE THREAD

**Issue by dominic-sps** [inukshuk/anystyle-parser#72]
1. Can I have comments in my training file
e.g.
```
<!-- Book type -->
<author> Barry Wilkinson, </author> ... <date> 1987. </date>
<!-- Journal type -->
<author> M. Kitsuregawa</author> ... <date> 1983. </date>
```
2. There is a use case where I need to use different models. Is it possible?
3. Need an example for saving model file by giving the path variable.

**Comment by inukshuk** [comment]
1. There's currently no support for comments, no. You'd have to strip out comments before you pass the data to the parser.
2. Sure; you can set the parser's `options[:model]` to any path you like and call `reload` on the parser. Or, in you case it's probably better two create two parser instances, each with its own model.
3. The `parser.model` returns [a Wapiti model on which you can call `save` with a path](https://github.com/inukshuk/wapiti-ruby#creating-a-model)

**Comment by inukshuk** [comment]
Tracked by #80
