### ISSUE TITLE
anystyle.io: Certificate Error / 502 / Bad Gateway

### ISSUE THREAD

**Issue by urspx** [inukshuk/anystyle-parser#74]
Hi,

I've been having an issue with the website for about two weeks...

Chrome says the following:
> Your connection is not private

> NET::ERR_CERT_DATE_INVALID

>This server could not prove that it is anystyle.io; its security certificate expired 14 days ago. This may be caused by a misconfiguration or an attacker intercepting your connection. Your computer's clock is currently set to Wednesday, October 4, 2017. Does that look right? If not, you should correct your system's clock and then refresh this page.

if I ignore the warning, it throws a 502 / Bad Gateway

Firefox Nightly likewise complains:
> Your connection is not secure
> 
> The owner of anystyle.io has configured their website improperly. To protect your information from being stolen, Nightly has not connected to this website.
> 
> This site uses HTTP Strict Transport Security (HSTS) to specify that Nightly may only connect to it securely. As a result, it is not possible to add an exception for this certificate.

and the more detailed error is:
> anystyle.io uses an invalid security certificate. The certificate expired on 21.September.2017, 05:28. The current time is 4.October.2017, 13:53. Error code: SEC_ERROR_EXPIRED_CERTIFICATE 

... and Safari says the following: 
> "Safari can't open the Page "https://anystyle.io" because the server unexpectedly dropped the connection. This sometimes occurs when the server is busy. Wait for a few minutes, then try again"

Thank you!

**Comment by inukshuk** [comment]
Thanks for reporting. Can you try again? Should be working now.

**Comment by urspx** [comment]
Yes, it does – amazing, Thank You!

**Comment by urspx** [comment]
Hi, sorry to open this again – it seems to be back to:

> 502 Bad Gateway
> 
> nginx/1.12.0

**Comment by inukshuk** [comment]
Yeah, sorry, it's just a tiny virtual server and runs out of memory quickly. Thanks the ping -- should be back up again.
