### ISSUE TITLE
Bibtex export

### ISSUE THREAD

**Issue by martindoerr2** [inukshuk/anystyle-parser#81]
The parser interprets  "and" as in "LEWIS, P., AND MARTINEZ, K. 2006. ..." as author. If trained to use the tag "unknown" for "AND", the bibtex export misses the last author.

**Comment by inukshuk** [comment]
Parsing references to BibTeX is a two-step process: the first part is segmentation of a references into contiguous segments (author, date, title, etc.). In the second step (normalization) individual segments are parsed further (e.g., authors are parsed into individual names, split into given and family names etc.). For that reason, labeling parts of the author segment (like the 'and' between names) individually will lead to worse results.

If the name parser (during normalization) produces bad results for your format, the best approach is to tweak name normalization or use an output format that skips normalization and normalize yourself. In the latter case you can also opt to tag tokens like 'and' differently and have your own post-processing rely on that information (my own approach was to label the author string as a whole and rely on deterministic name parsing for further analysis).
