### ISSUE TITLE
Publish data from anystyle.io to the repository

### ISSUE THREAD

**Issue by fjorgemota** [inukshuk/anystyle-parser#85]
Hello!

I have a problem where I need to parse a few references (less than 450 references, to be more exact) and I'm trying to use `anystyle` to parse these references.

At first, I tried to use `anystyle-parser` gem because it is offline. But I found a little problem: The data from the gem is actually VERY out of date comparing with the data from the site. Actually, to be exact, the last commit updating [the train data](https://github.com/inukshuk/anystyle-parser/blob/master/resources/train.txt) is from 2014, while the data from the site was updated less than 1 hour ago as I post this commit.

Because of this problem, the references are successfully parsed on the site, but not locally using the gem!

I know that [I can train the parser](https://github.com/inukshuk/anystyle-parser#unhappy-with-the-results), but I do not see the reason to do that if the website is actually working correctly to parse the references that I tested.

And yes, I could use the website directly, but for this problem I really wish to not need to use a website - with a private API (even if I can obtain the API key by just passing an e-mail) - to get the data from the references correctly. 

Thanks.

**Comment by inukshuk** [comment]
I'm afraid you'll have to wait: there's currently a major re-write and improvement underway on the Gem; when that is ready, you'll be able to install and use a much improved version of the parser (better than the one hosted on anystyle.io) and more advanced training data, too. Until that is ready, I won't the resources to update the old data.

If this is really urgent, I can push some of the recent training data from the website here, if you want, but since the data is being collected without supervision the quality varies greatly (note that even on the website the model is reset to the core data from 2014 regularly).

**Comment by fjorgemota** [comment]
Hey.

First, thanks for the fast answer! It is very much appreciated! =)

Second, I will not a frequent user of the `gem` (mainly because i'm not a ruby developer and i'm just trying to solve this problem I have here with these references).

However, i'm happy that the work continues, and would be really thankful if the data actually used on the website is uploaded to some place so I can download it. As I have less than 450 references, and most of the problematic references really worked according to my tests on the website, I think it will be really helpful to use the data of the website, so the quality do not affects too much on this case (plus: I just want to get the titles of the references, to identify duplicated references on the dataset).

Thanks in advance. =)

**Comment by inukshuk** [comment]
Alright, there you go: here's the [current training data](https://gist.github.com/inukshuk/2d5e6c2dabc14b9544f9b286b0efff0e). The first half or so is the old data from the 2014, the rest would be the most recently trained data from anystyle.io.

**Comment by fjorgemota** [comment]
Hey, thank you!

I tried here with your data and unfortunately it did not worked as I expect (it failed with some records). I tried to train the algorithm with some formats but it broke with some other records. I think it's the fault of the machine learning involved, but ok.

Anyway, thank you for the help and for the fast answer. And success with your project! :+1:
