### ISSUE TITLE
Some items are left without a type, throws an error

### ISSUE THREAD

**Issue by a-fent** [inukshuk/anystyle-parser#92]
normalizers/type.rb can leave a parsed item without an assigned type, which will throw an error when code within anystyle relies on it being there. 

I think the simple fix is to add         
     else
          'misc'

to the bottom of the case... statement in normalizers/type.rb

**Comment by namyra** [comment]
Since the new architecture allows you to skip normalizers if you so wish, a fallback in normalizers/type.rb wouldn't guarantee that an item has a type before exporting to bibtex format as that normalizer might never be run.

I've added a fallback in format_bibtex() in parser.rb instead.
