### ISSUE TITLE
Output URLs get truncated in JSON & BibTeX

### ISSUE THREAD

**Issue by urspx** [inukshuk/anystyle-parser#93]
Hi,

JSON URL output seems to cut apart URLs on certain symbols. For instance, the following references:

> Brownsword, R. (2006). Neither East Nor West, is Mid-West Best? SCRIPT-ed, 3(1), 16-33. Retrieved from http://ssrn.com/abstract=1127125.
> Barbry, E. (2012). The Internet of Things, Legal Aspects: What Will Change (Everything)…, Communications and Strategies (87), 83–100. Retrieved from http://papers.ssrn.com/sol3/papers.cfm?abstract_id=2304137

produce JSON output that looks like this:
`"URL": "http://ssrn.com/abstract"` & `"URL":  "http://papers.ssrn.com/sol3/papers.cfm"`
and the BibTeX has the same issue
` url = {http://papers.ssrn.com/sol3/papers.cfm}` & ` url = {http://ssrn.com/abstract},`
while the XML output looks correct
`<url>http://ssrn.com/abstract=1127125.</url>`& `<url>http://papers.ssrn.com/sol3/papers.cfm?abstract_id=2304137</url>`.

Based on issue #64, it seems like it might be an issue with the normalizer? Here, though, the URLs are 'coming in' correctly, and the symbols in question aren't spaces – they're ? and =, which are common elements in SSRN URLs.

Would there be a straightforward way to change this behavior?

**Comment by inukshuk** [comment]
You're right, this is an issue with the normalizer. We've already fixed this in the current version (the master branch here, but not ready for release yet). In the meantime, the only workaround for the current version would be to monkey-patch the normalizer or use an output format which does not normalize the output (hash or xml).

**Comment by urspx** [comment]
Ah, amazing – thank you for all your work on Anystyle!

Will the current version be made the back-end for the web app once it's ready?

**Comment by inukshuk** [comment]
I hope we'll do that eventually, yes. The new version is much improved and I'd like it to be easily accessible via the website, but I don't want to make any promises, because these things take time : )
